### ISSUE TITLE
Pseudotime Alignment Input Parameters

### ISSUE THREAD

**Issue by RZiffra** [quadbiolab/primate_cerebral_organoids#1]
Hello,

I would like to use your pseudotime alignment code and was hoping you could pass along the formatting requirements for the input ref/query expression matrices and pseudotime values.

Thanks,
Ryan

**Comment by zhisonghe** [comment]
Hi, Ryan,

Sorry for the late reply.

If you want to use the align_pt_traj function in pt_alignment.r, expr_ref and expr_query should be matrices of the same number of rows (for genes to be used for distance calculation), while their column number being the number of cells in the reference and query trajectory, respectively. Meanwhile, pt_ref and pt_query should be given, both as a vector of length of the cell number in the two trajectories. expr_ref (expr_query) columns and pt_ref (pt_query) should share the same order of cells.

Alternatively, if you want to use trunc_align_pt_traj, expr_ref, expr_query, pt_ref and pt_query is the same as in align_pt_traj. The other two parameters, alt_ref and alt_query which will be used to determine truncated points, are set by default to be expr_ref and expr_query. If you want to change them, keep the column orders identical as expr_ref and expr_query, while rows can be changed to another gene sets or dimension reduction results.

I hope this information is helpful. I will update the description later to the archive. Thanks for asking.

Best,
Zhisong


On 17 Oct 2019, at 00:03, RZiffra <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello,

I would like to use your pseudotime alignment code and was hoping you could pass along the formatting requirements for the input ref/query expression matrices and pseudotime values.

Thanks,
Ryan

**Comment by RZiffra** [comment]
Great, thanks Zhisong!
